version: "3.8"

services:
  django:
    build:
      context: ./cesspool-backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./cesspool-backend:/cesspool-backend
    command: >
      sh -c "python3 manage.py collectstatic &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./cesspool-backend/.env.dev
    depends_on:
      - db

  db:
    image: "postgres:14.1-alpine"
    env_file:
      - ./cesspool-backend/.env.dev
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: 
      context: ./cesspool-backend
    command: celery -A cesspool_backend worker -l info
    volumes:
      - ./cesspool-backend:/cesspool-backend
    env_file:
      - ./cesspool-backend/.env.dev
    depends_on:
      - db
      - redis
      - django

  celery_beat:
    restart: always
    build: 
      context: ./cesspool-backend
    command: celery -A cesspool_backend beat -l info
    volumes:
      - ./cesspool-backend:/cesspool-backend
    env_file:
      - ./cesspool-backend/.env.dev
    depends_on:
      - db
      - redis
      - django