version: "3.8"

services:
  react:
    build:
      context: ./cesspool-frontend

  django:
    build:
      context: ./cesspool-backend
    ports:
      - "8000:8000"
    restart: 
      always
    volumes:
      - static-data:/vol/web
      - ./cesspool-backend:/cesspool-backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             python3 manage.py wait_for_db &&
             uwsgi --socket :9000 --workers 4 --master --enable-threads --module cesspool_backend.wsgi"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_MQTT_HOST=${DJANGO_MQTT_HOST}
      - DJANGO_MQTT_USERNAME=${DJANGO_MQTT_USERNAME}
      - DJANGO_MQTT_PASS=${DJANGO_MQTT_PASS}
      - DJANGO_MQTT_PORT=${DJANGO_MQTT_PORT}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASS=${DJANGO_EMAIL_HOST_PASS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - IS_MAIN=1
    depends_on:
      - db

  db:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  proxy:
    build:
      context: ./proxy
    restart: 
      always
    depends_on:
      - django
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: 
      context: ./cesspool-backend
    command: ['python3', '-m', 'celery', '-A', 'cesspool_backend', 'worker', '-l', 'info']
    volumes:
      - ./cesspool-backend:/cesspool-backend
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_MQTT_HOST=${DJANGO_MQTT_HOST}
      - DJANGO_MQTT_USERNAME=${DJANGO_MQTT_USERNAME}
      - DJANGO_MQTT_PASS=${DJANGO_MQTT_PASS}
      - DJANGO_MQTT_PORT=${DJANGO_MQTT_PORT}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASS=${DJANGO_EMAIL_HOST_PASS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    depends_on:
      - db
      - redis
      - django

  celery_beat:
    restart: always
    build: 
      context: ./cesspool-backend
    command: ['python3', '-m', 'celery', '-A', 'cesspool_backend', 'beat', '-l', 'info']
    volumes:
      - ./cesspool-backend:/cesspool-backend
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_MQTT_HOST=${DJANGO_MQTT_HOST}
      - DJANGO_MQTT_USERNAME=${DJANGO_MQTT_USERNAME}
      - DJANGO_MQTT_PASS=${DJANGO_MQTT_PASS}
      - DJANGO_MQTT_PORT=${DJANGO_MQTT_PORT}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASS=${DJANGO_EMAIL_HOST_PASS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    depends_on:
      - db
      - redis
      - django

volumes:
  postgres-data:
  static-data: