version: "3.8"

services:
  django:
    build:
      context: ./cesspool-backend
    ports:
      - "8000:8000"
    restart:
      always
    volumes:
      - ./cesspool-backend:/cesspool-backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    enviroment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
      - DJANGO_SECRET_KEY=yzpy-d%1ixo601b3z7kjh7l8w*ur427vg=cjssc+a0ei2tgv8e
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=KettuHeslo
    depends_on:
      - db

  db:
    image: "postgres:14.1-alpine"
    enviroment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=KettuHeslo
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: 
      context: ./cesspool-backend
    command: celery -A cesspool_backend worker -l info
    volumes:
      - ./cesspool-backend:/cesspool-backend
    enviroment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
      - DJANGO_SECRET_KEY=yzpy-d%1ixo601b3z7kjh7l8w*ur427vg=cjssc+a0ei2tgv8e
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=KettuHeslo
    depends_on:
      - db
      - redis
      - django

  celery_beat:
    restart: always
    build: 
      context: ./cesspool-backend
    command: celery -A cesspool_backend beat -l info
    volumes:
      - ./cesspool-backend:/cesspool-backend
    enviroment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
      - DJANGO_SECRET_KEY=yzpy-d%1ixo601b3z7kjh7l8w*ur427vg=cjssc+a0ei2tgv8e
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=KettuHeslo
    depends_on:
      - db
      - redis
      - django