# Generated by Django 4.1.4 on 2023-01-28 22:46

import cesspool.utils
import cesspool.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("location", "0007_alter_city_options"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cesspool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delete_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        default=cesspool.utils.generate_cesspool_code,
                        max_length=10,
                        unique=True,
                        validators=[cesspool.validators.validate_machine_code],
                    ),
                ),
                ("about", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subscription_expiration_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.city",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ["related_to_cesspool", "Can be related to the cesspool"]
                ],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("level_m", models.FloatField()),
                ("level_percent", models.FloatField()),
                ("battery", models.FloatField()),
                (
                    "cesspool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cesspool.cesspool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CesspoolToUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=None, default=None, max_length=25, null=True
                    ),
                ),
                ("contact_at_level", models.FloatField(default=80.0)),
                ("is_super_owner", models.BooleanField(default=False)),
                (
                    "cesspool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cesspool.cesspool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "cesspool")},
            },
        ),
    ]
