# Generated by Django 4.1.7 on 2023-03-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CesspoolNotRespondingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sand', models.BooleanField(default=False)),
                ('cesspool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesspool.cesspool')),
            ],
        ),
        migrations.CreateModel(
            name='CesspoolLowBatteryProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sand', models.BooleanField(default=False)),
                ('cesspool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesspool.cesspool')),
            ],
        ),
        migrations.CreateModel(
            name='CesspoolHightLevelNotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sand', models.BooleanField(default=False)),
                ('ctu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesspool.cesspooltouser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CesspoolDeadBatteryProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sand', models.BooleanField(default=False)),
                ('cesspool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesspool.cesspool')),
            ],
        ),
    ]
