# Generated by Django 4.1.7 on 2023-03-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0003_inviteusertocesspool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteUserToCesspool',
        ),
    ]
