# Generated by Django 4.1.7 on 2023-03-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0004_delete_inviteusertocesspool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cesspool',
            options={'permissions': [['related_to_cesspool', 'Can be related to the cesspool'], ['edit_users', 'Can edit users']]},
        ),
    ]
