# Generated by Django 4.1.7 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0007_cesspool_demo_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_on_demo_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='mqtt_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
