# Generated by Django 4.1.7 on 2023-04-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0008_record_created_on_demo_mode_record_mqtt_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cesspool',
            old_name='demo_mode',
            new_name='debug_mode',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='created_on_demo_mode',
            new_name='created_on_debug_mode',
        ),
    ]
