# Generated by Django 4.1.7 on 2023-04-20 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0008_alter_city_options'),
        ('subscription', '0006_alter_subscription_month_paying'),
        ('cesspool', '0009_rename_demo_mode_cesspool_debug_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesspool',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cesspool',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
        migrations.AlterField(
            model_name='cesspool',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscription'),
        ),
    ]
