# Generated by Django 4.1.7 on 2023-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0010_cesspool_created_by_alter_cesspool_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='battery_volt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
