# Generated by Django 4.1.7 on 2023-04-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesspool', '0011_record_battery_volt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='battery_volt',
            new_name='battery_voltage',
        ),
    ]
