# Generated by Django 4.0.6 on 2022-08-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_max_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
