# Generated by Django 4.0.6 on 2022-08-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_alter_machine_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.FloatField(default=0.0),
        ),
    ]
