# Generated by Django 4.0.4 on 2022-08-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_alter_record_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='max_level',
        ),
        migrations.AddField(
            model_name='record',
            name='level_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='record',
            name='battery',
            field=models.FloatField(default=0.0),
        ),
    ]
