# Generated by Django 4.1 on 2022-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0005_remove_machine_max_level_record_level_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="battery",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="record",
            name="level",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="record",
            name="level_percent",
            field=models.FloatField(default=None),
        ),
    ]
