# Generated by Django 4.1 on 2022-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0007_alter_record_battery_alter_record_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="battery",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="record",
            name="level",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="record",
            name="level_percent",
            field=models.FloatField(default=0.0),
        ),
    ]
