# Generated by Django 4.1 on 2022-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0010_alter_record_battery_alter_record_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mqtt",
            field=models.BooleanField(default=True),
        ),
    ]
