# Generated by Django 4.1 on 2022-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0011_machine_mqtt"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="autocorrect",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="notification",
            field=models.BooleanField(default=True),
        ),
    ]
