# Generated by Django 4.1 on 2022-09-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0013_machinedeleteaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinedeleteaction",
            name="machine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="machine.machine"
            ),
        ),
    ]
