# Generated by Django 4.1 on 2022-09-01 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0014_alter_machinedeleteaction_machine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinedeleteaction",
            name="date",
        ),
        migrations.RemoveField(
            model_name="machinedeleteaction",
            name="machine",
        ),
    ]
