# Generated by Django 4.1 on 2022-09-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0015_remove_machinedeleteaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedeleteaction",
            name="date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="machinedeleteaction",
            name="machine",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="machine.machine",
            ),
        ),
    ]
