# Generated by Django 4.1 on 2022-09-01 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0016_machinedeleteaction_date_machinedeleteaction_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinedeleteaction",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="machinedeleteaction",
            name="machine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="machine.machine"
            ),
        ),
    ]
