# Generated by Django 4.0.7 on 2022-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0019_machine_hight_level_machineoldrecordproblem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedeathbatteryproblem',
            name='detail',
            field=models.CharField(default='Vybitá bateria', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinedeathbatteryproblem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'warning'), (1, 'error')], default=1),
        ),
        migrations.AlterField(
            model_name='machinehightlevelproblem',
            name='detail',
            field=models.CharField(default='Vysoká hladina', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinehightlevelproblem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'warning'), (1, 'error')], default=1),
        ),
        migrations.AlterField(
            model_name='machinelowbatteryproblem',
            name='detail',
            field=models.CharField(default='Slabá bateria', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinelowbatteryproblem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'warning'), (1, 'error')], default=1),
        ),
        migrations.AlterField(
            model_name='machinenorecordproblem',
            name='detail',
            field=models.CharField(default='Nenašli sa záznmy', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinenorecordproblem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'warning'), (1, 'error')], default=0),
        ),
        migrations.AlterField(
            model_name='machinenotitleproblem',
            name='detail',
            field=models.CharField(default='Není natavený názov', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinenotitleproblem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'warning'), (1, 'error')], default=0),
        ),
        migrations.AlterField(
            model_name='machineoldrecordproblem',
            name='detail',
            field=models.CharField(default='Dlhšiu dobu sa neozíva', max_length=20),
        ),
        migrations.AlterField(
            model_name='machineoldrecordproblem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'warning'), (1, 'error')], default=1),
        ),
    ]
