# Generated by Django 4.0.7 on 2022-09-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0020_alter_machinedeathbatteryproblem_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinenorecordproblem',
            name='is_sand',
        ),
        migrations.RemoveField(
            model_name='machinenotitleproblem',
            name='is_sand',
        ),
    ]
