# Generated by Django 4.0.7 on 2022-09-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0021_remove_machinenorecordproblem_is_sand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedeathbatteryproblem',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='machinedeathbatteryproblem',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='machinehightlevelproblem',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='machinehightlevelproblem',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='machinelowbatteryproblem',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='machinelowbatteryproblem',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='machinenorecordproblem',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='machinenorecordproblem',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='machinenotitleproblem',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='machinenotitleproblem',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='machineoldrecordproblem',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='machineoldrecordproblem',
            name='importance',
        ),
    ]
