# Generated by Django 4.0.7 on 2022-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0022_remove_machinedeathbatteryproblem_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
