# Generated by Django 4.0.7 on 2022-10-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0025_alter_machine_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='autocorrect',
        ),
    ]
