# Generated by Django 4.1.4 on 2022-12-10 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("machine", "0026_remove_machine_autocorrect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="hight_level",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="title",
        ),
        migrations.CreateModel(
            name="MachineToUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=14, null=True)),
                ("hight_level", models.IntegerField(default=85)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machine.machine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
