# Generated by Django 4.1.4 on 2022-12-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0027_remove_machine_hight_level_remove_machine_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="user",
        ),
    ]
