# Generated by Django 4.1.4 on 2022-12-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        ("machine", "0029_alter_machine_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="city",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.city",
            ),
            preserve_default=False,
        ),
    ]
