# Generated by Django 4.1.4 on 2023-01-28 20:44

from django.db import migrations, models
import subscription.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10, unique=True)),
                ("about", models.CharField(max_length=50)),
                ("mqtt", models.BooleanField(default=False)),
                ("email_notf", models.BooleanField(default=False)),
                ("sms_notf", models.BooleanField(default=False)),
                (
                    "max_owners",
                    models.IntegerField(
                        default=1,
                        validators=[subscription.validators.validate_max_owners],
                    ),
                ),
            ],
        ),
    ]
