# Generated by Django 4.1.7 on 2023-03-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='month_paying',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
