# Generated by Django 4.1.7 on 2023-03-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_month_paying'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='change_part',
            field=models.BooleanField(default=False),
        ),
    ]
