# Generated by Django 4.1.7 on 2023-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_change_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='month_paying',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
