# Generated by Django 4.1.7 on 2023-03-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_month_paying'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='change_part',
            new_name='change_parts',
        ),
    ]
