# Generated by Django 4.1.4 on 2022-12-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_alter_city_admin_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="psc",
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.CharField(default="x", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="title",
            field=models.CharField(max_length=25),
        ),
    ]
