# Generated by Django 4.1.4 on 2022-12-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_remove_city_psc_city_district_alter_city_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("title", "district")},
        ),
    ]
