# Generated by Django 4.1.4 on 2022-12-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_alter_city_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"permissions": []},
        ),
        migrations.RenameField(
            model_name="city",
            old_name="admin_manager",
            new_name="manager",
        ),
    ]
