# Generated by Django 4.1.4 on 2022-12-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_alter_city_options_rename_admin_manager_city_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="delete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
