# Generated by Django 4.1.4 on 2023-01-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_city_delete_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "permissions": [
                    ["export_data", "Can export data"],
                    ["be_city_admin", "Can be an admin of city"],
                ]
            },
        ),
    ]
