# Generated by Django 4.1.7 on 2023-03-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'permissions': [['export_data', 'Can export data'], ['be_city_admin', 'Can be an admin of city'], ['manage_city', 'Can manage cities']]},
        ),
    ]
