# Generated by Django 4.1.7 on 2023-03-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_activateusertoken_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [['manage_account', 'Can manage accounts']]},
        ),
    ]
