# Generated by Django 4.0.7 on 2022-10-08 22:35

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_resetpasswordtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='code',
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='expired_date',
            field=models.DateTimeField(default=account.models.get_reset_password_token_date),
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(default=account.models.generate_code, max_length=8),
        ),
        migrations.CreateModel(
            name='ActivateUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=account.models.generate_code, max_length=8)),
                ('expired_date', models.DateTimeField(default=account.models.get_activate_user_token_date)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
